# Part 1 Answers:
1. Line 9 will print the following: "values added:  20" to the console. There is no error that will occur; we are witnessing valid syntax.
2. Line 13 will print the following: "final result:  20" to the console. There is no error that will occur; we are witnessing valid syntax.
3. Line 9 will print the following: "values added:  20" to the console. There is no error that will occur; we are witnessing valid syntax.
4. This code shall return an error because we have used the keyword *let* to define the variable *result*. Therefore, when running line 13, we get an error because the call to result is not in the scope where it was originally declared.
5. This code shall return an error because we are trying to modify a const before line 9. We have learned that a const has fixed definition, and we are not able to change its value at anytime in a function once declared.
6. This code shall return an error because we are actively trying to modify the value of a const in line 7. This is syntactically no correct and therefore the console throws an error for the running of the whole function.
7. 